//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.05.10 at 10:47:03 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.soap.project1/gen17", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package project1.soap.com.gen17;
